version: '3.8'

# Ensure we use alpine wherever possible
x-image:
    - &node node:16-alpine
    - &nginx nginx:stable-alpine3.17-slim
    - &php php:8.2-fpm-alpine
    - &mysql mariadb:10.11.4
    - &redis redis:6.0.20-alpine
    - &mailhog mailhog/mailhog:v1.0.1
    - &pma phpmyadmin:5.2

services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                NGINX_IMAGE: *nginx
        container_name: ${APP_NAME}_web
        volumes:
            - './docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf'
            - './:/var/www/html'
        ports:
            - 80:80
            - 443:443
        networks:
            - dockerize-laravel
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile.prod
            args:
                PHP_IMAGE: *php
                NODE_IMAGE: *node
        container_name: ${APP_NAME}_app
        volumes:
            - './:/var/www/html'
        networks:
            - dockerize-laravel
        depends_on:
            - mysql
            - redis

    mysql:
        image: *mysql
        container_name: ${APP_NAME}_db
        restart: unless-stopped
        ports:
            - ${DB_PORT:-3306}:3306
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_ROOT_PASSWORD=root
        volumes:
            - 'mariadbdata:/var/lib/mysql'
        networks:
            - dockerize-laravel

    redis:
        image: *redis
        container_name: ${APP_NAME}_redis
        ports:
            - ${REDIS_PORT:-6379}:6379
        restart: unless-stopped
        volumes:
            - 'redisdata:/data'
        networks:
            - dockerize-laravel

volumes:
    mariadbdata:
    redisdata:

networks:
    dockerize-laravel:
