version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: ${APP_NAME}_web
        volumes:
            - './docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - 80:80
        networks:
            - dockerize-laravel
        depends_on:
            - mysql
            - app

    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ${APP_NAME}_app
        volumes:
            - './:/var/www/html'
        networks:
            - dockerize-laravel
        ports:
            - 5173:5173 # Essential for vite.

    mysql:
        image: mariadb:10.11.4
        container_name: ${APP_NAME}_db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - 'mariadbdata:/var/lib/mysql'
        networks:
            - dockerize-laravel


volumes:
    mariadbdata:

networks:
    dockerize-laravel:
