version: '3.8'

# Ensure we use alpine wherever possible
x-image:
    - &node node:16-alpine
    - &nginx nginx:stable-alpine3.17-slim
    - &php php:8.2-fpm-alpine
    - &mysql mariadb:10.11.4
    - &redis redis:6.0.20-alpine
    - &mailhog mailhog/mailhog:v1.0.1
    - &pma phpmyadmin:5.2

services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                NGINX_IMAGE: *nginx
        container_name: ${APP_NAME}_web
        volumes:
            - './docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf'
            - './:/var/www/html'
        ports:
            - 80:80
        networks:
            - dockerize-laravel
        depends_on:
            - mysql
            - app
            - node
            - redis

    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                PHP_IMAGE: *php
        container_name: ${APP_NAME}_app
        volumes:
            - './:/var/www/html'
        networks:
            - dockerize-laravel
        depends_on:
            - mysql
            - node
            - redis

    mysql:
        image: *mysql
        container_name: ${APP_NAME}_db
        restart: unless-stopped
        ports:
            - ${DB_PORT:-3306}:3306
        environment:
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_ROOT_PASSWORD=root
        volumes:
            - 'mariadbdata:/var/lib/mysql'
        networks:
            - dockerize-laravel

    node:
        image: *node # Todo set to global environment variables with extension fields, anchors
        container_name: ${APP_NAME}_node
        ports:
            - 5173:5173
        working_dir: /var/www/html
        volumes:
            - './:/var/www/html'
        command: ["sh", "-c", "npm install && npm run dev"]
        networks:
            - dockerize-laravel
        restart: unless-stopped

    redis:
        image: *redis
        container_name: ${APP_NAME}_redis
        ports:
            - ${REDIS_PORT:-6379}:6379
        restart: unless-stopped
        volumes:
            - 'redisdata:/data'
        networks:
            - dockerize-laravel

    mailhog:
        image: *mailhog
        container_name: ${APP_NAME}_mail
        ports:
            - "${MAIL_PORT}:8025"
        networks:
            - dockerize-laravel

    pma:
        image: *pma
        container_name: ${APP_NAME}_pma
        depends_on:
            - mysql
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        networks:
            - dockerize-laravel

volumes:
    mariadbdata:
    redisdata:

networks:
    dockerize-laravel:
