on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Symlink env file
        run: ln -fs .env.example .env

      - name: Run docker containers
        run: docker compose up -d

      - name: List container files
        run: docker exec -i dockerize-laravel_app ls -la

      - name: Composer install
        run: docker exec -i dockerize-laravel_app composer install

      - name: Run test inside container
        run: docker exec -i dockerize-laravel_app php artisan test

      - name: Build assets
        run: docker exec -i dockerize-laravel_node npm run build

  publish_to_docker_hub:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: List contents
        run: ls -la
