on:
  push:
    branches:
      - master

env:
  APP_NAME: dockerize-laravel

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Symlink env file
        run: ln -fs .env.example .env

      - name: Run docker containers
        run: docker compose up -d

      - name: Composer install
        run: docker exec -i ${{ env.APP_NAME }}_app composer install

      - name: Check coding standards
        run: docker exec -i ${{ env.APP_NAME }}_app ./vendor/bin/pint --test

      - name: Build assets
        run: docker exec -i ${{ env.APP_NAME }}_node npm run build

      - name: Run backend tests
        run: docker exec -i ${{ env.APP_NAME }}_app php artisan test

  publish_to_docker_hub:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: List contents
        run: ls -la
