name: CI
on:
    workflow_dispatch: # Ability to manually run this workflow from ui.
    push:
        branches:
            - "*"

env:
    APP_NAME: dockerize-laravel

jobs:
    pipelines:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Back up .env.prod
              run: cp .env.prod .env.prod.bak

            - name: Set env ci file
              run: mv -f .env.ci .env.prod
              # We set .env.ci as prod so that, php docker build automatically replaces the current .env.prod to .env while bringing the production docker file up.

            - name: Run docker containers
              run: docker compose -f docker-compose.prod.yml --env-file=.env.prod up -d
              # Todo cache this.

            - name: Composer install
              run: docker exec -i ${{ env.APP_NAME }}_app composer install

            - name: Check coding standards
              run: docker exec -i ${{ env.APP_NAME }}_app ./vendor/bin/pint --test

            - name: Run all php tests
              run: docker exec -i ${{ env.APP_NAME }}_app php artisan test

            - name: Shut down containers
              run: docker compose down

            - name: Revert back env files
              run: mv -f .env.prod .env.ci && mv -f .env.prod.bak .env.prod

    publish_to_docker_hub:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master' # Here if branch is master only we publish to docker hub.
        needs: [pipelines]
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Login to docker hub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Extract metadata (tabs, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b
              with:
                  images: sudiprai277/dockerize-laravel #The namespace and name for the Docker image you are building/pushing to Docker Hub.

            - name: Build and push docker image
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            # - name: Build application docker image
            #   env:
            #       IMAGE_TAG: ${{ github.sha }}
            #   run: docker build -t ${{ DOCKERHUB_USERNAME }}/${{ APP_NAME }}:${{ IMAGE_TAG }} .

    deploy_to_production:
        if: github.ref == 'refs/heads/master' # Here if branch is master only.
        runs-on: ubuntu-latest
        needs: [pipelines, publish_to_docker_hub]
        environment: production
        concurrency: production # Only one production job runs at any point of time.
        cancel-in-progress: true
        steps:
            - name: Echo github context
              run: echo "$GITHUB_CONTEXT"
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}

            - name: Deploy
              run: ls -la # Run actual script for deploy to do.
