name: CI
on:
    workflow_dispatch: # Ability to manually run this workflow from ui.
    push:
        branches:
            - "*"

env:
    APP_NAME: dockerize-laravel

jobs:
    deploy_to_production:
        if: github.ref == 'refs/heads/master' # Here if branch is master only.
        runs-on: ubuntu-latest
        needs: [pipelines, publish_to_docker_hub]
        environment: production
        concurrency: production # Only one production job runs at any point of time.
        steps:
            - name: Install ssh keys
              run: |
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            - name: Deploy
              run: |
                  ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
                  "cd ${{ secrets.WORK_DIR }} && \
                  git pull origin master && \
                  docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build && \
                  docker exec ${{ env.APP_NAME }}_app /bin/sh ./scripts/post-deploy.sh && \
                  exit"
            - name: Cleanup
              run: rm -rf ~/.ssh
